# This is a basic workflow to help you get started with Actions

name: Code Base Formatter

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  formatting-java-files:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: __Clone Repository
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      
      #https://github.com/axel-op/googlejavaformat-action
      - name: __Format Code Base
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
