# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Deploy as Github & Maven Packages

on:
  push:
    branches: [main]
   

jobs:
  deploy-process:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Cloning repository
      uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

# Input parameters can be found at https://github.com/marketplace/actions/checkstyle-for-java
    - name: Check code style
      uses: dbelyaev/action-checkstyle@master
      env:
          github_token: ${{ github.token }}
      with:
          checkstyle_config: google_style.xml
          reporter: github-pr-review
          level: warning
          fail_on_error: true
          
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
